[build-system]
requires = [
    "setuptools",
]

[project]
name = "pysubnettree"
dynamic = ["version"]
description = "Map subnets in CIDR notation to Python objects"
readme = "README"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'License :: OSI Approved :: BSD License',
    'Operating System :: POSIX :: Linux',
    'Operating System :: POSIX :: BSD :: FreeBSD',
    'Operating System :: MacOS :: MacOS X',
    'Programming Language :: Python :: 3',
    'Topic :: System :: Networking',
    'Topic :: Utilities',
]

[project.license]
text = "BSD"

[[project.maintainers]]
name = "The Zeek Project"
email = "info@zeek.org"
